name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Startup
        uses: actions/checkout@v3

      - name: Download PHP Release
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: PHP-Linux-x86_64-PM5.tar.gz
          repo: NetherGamesMC/php-build-scripts
          version: "tags/php-8.2-latest"

      - name: Unpack PHP Release
        run: tar -xzvf PHP-Linux-x86_64-PM5.tar.gz

      - name: Download Composer
        run: curl -o composer.phar "https://getcomposer.org/composer-stable.phar"

      - name: Config Composer
        run: ./bin/php7/bin/php composer.phar config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        run: ./bin/php7/bin/php composer.phar install --prefer-dist --no-interaction

      - name: Run Build
        run: ./bin/php7/bin/php -dphar.readonly=0 vendor/bin/pharynx -v -c -i .

      - name: Get plugin.yml information
        run: |
          name=$(grep -oP '(?<=name: ).*' plugin.yml || echo "unknown")
          version=$(grep -oP '(?<=version: ).*' plugin.yml || echo "unknown")

          echo "Name of plugin: $name"
          echo "Version of plugin: $version"

          echo "PLUGIN_NAME=$name" >> $GITHUB_ENV
          echo "PLUGIN_VERSION=$version" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: ${{ github.workspace }}/output.phar
          draft: false
          name: ${{ env.PLUGIN_NAME }} v${{ env.PLUGIN_VERSION }} Release
          tag: v${{ env.PLUGIN_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "The artifacts are kept up to date with the master branch"
          commit: ${{ github.sha }}
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true